### ISSUE TITLE
Error when using module_WGCNA

### ISSUE THREAD

**Issue by JamesWu7** [zhangjunpeng411/miRSM#1]
Hi! guys. U performed an amazing package to construct ceRNA networks. However, when I use the function, "module_WGCNA", some errors were reported, as following 

> modulegenes_WGCNA <- module_WGCNA(ceRExp = lncRExp,
                                  mRExp = mRExp,
                                   RsquaredCut = 0.8,
                                   num.ModuleceRs = 5,
                                   num.ModulemRs = 5)
**Error in summary.connection(connection) : invalid connection**
> 
When using function, "module_biclust", it will work properly.

Is there any way to fix this problem, thank u in advance.

**Comment by zhangjunpeng411** [comment]
You can check the solution at https://stackoverflow.com/questions/64519640/error-in-summary-connectionconnection-invalid-connection.
